global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
  
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']
  
  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking-service:3002']
  
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8000']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']